---
title: "1st-year-survey"
author: "Preetha"
date: "12/7/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages

```{r load-packages}
library(tidyverse)
```

## Load Data

```{r load-data}
first <- readr::read_csv('data/survey.csv')
```

### Data Cleaning

```{r, include = FALSE}
newfirst <- first %>% 
  mutate(college = `Are you enrolled in Trinity College of Arts and Sciences or the Pratt School of Engineering?`,
         hispanic = `Are you of Hispanic/Latino/Spanish origin?`,
         race = `How would you best describe yourself?`,
         gender = `What is your gender?`,
         sexor = `What is your sexual orientation?`,
         firstgen = `Are you a first-generation college student?`,
         athlete = `Are you a recruited varsity athlete?`,
         int = `Are you an international student?`,
         state = `Which state do you live in (please enter the postal abbreviation)?`,
         zip = `What is the ZIP Code of your home address?`,
         city = `What is your home city?`,
         country = `What is your home country?`,
         community = `What type of community are you from?`,
         income = `What do you estimate is your immediate family's total annual income?`,
         finaid = `Do you receive financial aid from Duke?`,
         major = `Which major are you most inclined towards?`,
         whyduke = `Which of the following most influenced your decision to attend Duke?`,
         greek = `How interested are you in Greek life at Duke?`,
         slgs = `How interested are you in non-Greek selective living groups at Duke?`,
         rush = `Are you more or less likely to rush if the recruitment process were to be online?`,
         whyrush = `What is your primary motivation for wanting to rush?`,
         livingwhere = `Which of the following best describes your living situation this semester?`,
         whyhome = `What was your primary reason for staying home?`,
         springliving = `Are you planning to come to campus/Durham in the spring?`,
         springplans = `What are your plans for the spring?`,
         covidrelief = `Did you receive additional COVID-19 relief funds from Duke? (in addition to financial aid package)`,
         amount = `What do you think of the amount received?`,
         testpos = `Have you tested positive for COVID-19 (while on campus)?`,
         knowpos = `Has someone you know tested positive for COVID-19 (while on campus)?`,
         compactOp = `Share your opinions on... - The Duke Compact`,
         enforcementOp = `Share your opinions on... - Duke's enforcement of the Duke Compact`,
         housingOp = `Share your opinions on... - First-year fall housing arrangements`,
         inperson = `How many in-person classes are you in this semester?`,
         focus = `Are you in a FOCUS?`,
         inpersonfocus = `How many of your FOCUS classes are in-person (not including the FOCUS “dinner”)?`,
         findcommunity = `Have you been able to find community this year?`,
         communitywhere = `Where have you primarily found community?`,
         pandemiccommunity = `How much do you think the pandemic has negatively affected your ability to find community?`,
         wearmask = `How likely are you to abide by the following elements of the Duke Compact: - Wearing a mask or face covering in all public spaces`,
         usesymmon = `How likely are you to abide by the following elements of the Duke Compact: - Monitoring and reporting symptoms through the SymMon app`,
         avoidgather = `How likely are you to abide by the following elements of the Duke Compact: - Avoiding large gatherings of 10+ people`,
         covidrelief = `Did you receive additional COVID-19 relief funds from Duke? (in addition to financial aid package)`,
         dodistance = `How likely are you to abide by the following elements of the Duke Compact: - Engaging in physical distancing`,
         peersmask = `How likely are your peers to abide by the following elements of the Duke Compact: - Wearing a mask or face covering in all public spaces`,
         peerssymmon = `How likely are your peers to abide by the following elements of the Duke Compact: - Monitoring and reporting symptoms through the SymMon app`,
         peersavoidgather = `How likely are your peers to abide by the following elements of the Duke Compact: - Avoiding large gatherings of 10+ people`,
         peersdistance = `How likely are your peers to abide by the following elements of the Duke Compact: - Engaging in physical distancing`,
         report = `How likely are you to report violations to the Duke Compact?`,
         summerplans = `Were your summer and/or travel plans affected by the pandemic?`,
         jobloss = `Has any member of your household lost their job or been furloughed due to the pandemic?`,
         coviddeath = `Have any of your family members or close contacts died from COVID-19?`,
         gpa = `What was your high school GPA (scaled on a 0 to 4.00 scale)?`,
         actorsat = `Did you take the SAT or ACT?`,
         sat = `What was your SAT combined score?`,
         act = `What was your ACT composite score?`,
         schooltype = `What type of secondary school did you attend?`,
         summerplans = `Were your summer and/or travel plans affected by the pandemic?`,
         collegecoun = `Did you hire a private college admissions counselor during the admissions process?`,
         numberapps = `How many colleges and universities did you apply to?`,
         acceptances = `How many colleges and universities were you accepted to?`,
         ed = `Did you apply to Duke via the Early Decision process?`,
         waitlist = `Were you accepted off the waitlist from Duke?`,
         firstchoice = `Was Duke your first choice?`,
         legacy = `Did any of your parents or siblings attend Duke?`,
         religion = `Which best describes your religion?`,
         howreligious = `How religious would you say you are?`,
         political = `How would you describe your political beliefs?`,
         voted = `Did you / are you planning to vote in the 2020 election?`,
         president = `Who did you vote for / who are you planning to vote for?`,
         wherevote = `Did you / are you planning to vote at your home or in Durham?`,
         primaryvote = `Did you vote in the primary election?`,
         lifestyle = `Have you done any of the following?`,
         mentalhealth = `Have you received treatment for your mental health before?`,
         continuedtreatment = `Are you currently receiving treatment for your mental health?`,
         chronicle = `In which format do you read The Chronicle?`)
```

```{r, include = FALSE}
newfirst
```

```{r religion-and-pres, fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(president,levels=c("Howie Hawkins", "Jo Jorgenson", "Joe Biden","Donald Trump"))), fill = religion))+
  geom_bar(position= "fill") +
  labs(title = "more support for trump among religiously affiliated students", 
       x = "", y = "") +
  scale_fill_discrete(name = "student's religious affiliation") +
  coord_flip() +
  theme_minimal()
```

```{r religiousity-and-pres, fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(president ,levels=c("Howie Hawkins", "Jo Jorgenson", "Joe Biden","Donald Trump"))), fill = (factor(howreligious ,levels=c("Not at all religious", "Not very religious", "Somewhat religious", "Religious", "Very religious")))))+
  geom_bar(position= "fill") +
  labs(title = "more support for trump among religious students", 
       x = "", y = "") +
  scale_fill_discrete(name = "religiousity") +
  coord_flip() +
  theme_minimal()
```

```{r home-and-pres-vote, fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = wherevote, fill = president))+
  geom_bar(position= "fill") +
  labs(title = "more biden voters among students who elected to vote in Durham", 
       x = "", y = "") +
  coord_flip() +
  theme_minimal()
```

```{r firstchoice-and-religion, fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(howreligious ,levels=c("Not at all religious", "Not very religious", "Somewhat religious", "Religious", "Very religious"))), fill = firstchoice))+
  geom_bar(position= "fill") +
  labs(title = "x", 
       x = "", y = "") +
  coord_flip() +
  theme_minimal()
```

```{r polleaning and religion, fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(political ,levels=c("Very liberal", "Somewhat liberal", "Moderate","Somewhat conservative", "Very conservative"))), fill = (factor(howreligious ,levels=c("Not at all religious", "Not very religious", "Somewhat religious", "Religious", "Very religious")))))+
  geom_bar(position= "fill") +
  labs(title = "increased liberal views, decreased religiosity", 
       x = "", y = "") +
  scale_fill_discrete(name = "religiousity") +
  coord_flip() +
  theme_minimal()
```

```{r income and pres vote, fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(income ,levels=c("Above $500,000","$250,000-$500,000", "$125,000-$250,000", "$80,000-$125,000","$40,000-$80,000", "Below $40,000"))), fill = president))+
  geom_bar(position= "fill") +
  labs(title = "income and presidential vote", 
       x = "", y = "") +
  coord_flip() +
  theme_minimal()
```

```{r income and greek, fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(greek ,levels=c("Extremely interested", "Very interested", "Moderately interested", "Slightly interested", "Not interested at all"))), fill = (factor(income ,levels=c("Above $500,000","$250,000-$500,000", "$125,000-$250,000", "$80,000-$125,000","$40,000-$80,000", "Below $40,000")))))+
  geom_bar(position= "fill") +
  labs(title = "income and interest in greek life", 
       x = "", y = "") +
  scale_fill_discrete(name = "income level") +
  coord_flip() +
  theme_minimal()
```

```{r legacy-and-politicalleaning, fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(political ,levels=c("Very liberal", "Somewhat liberal", "Moderate","Somewhat conservative", "Very conservative"))), fill = legacy))+
  geom_bar(position= "fill") +
  labs(title = "political leaning and legacy status", 
       x = "", y = "") +
  coord_flip() +
  theme_minimal()
```

```{r legacy-and-income, fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = legacy, fill = (factor(income ,levels=c("Above $500,000","$250,000-$500,000", "$125,000-$250,000", "$80,000-$125,000","$40,000-$80,000", "Below $40,000")))))+
  geom_bar(position= "fill") +
  labs(title = "legacy status and income", 
       x = "", y = "") +
  scale_fill_discrete(name = "income level") +
  coord_flip() +
  theme_minimal()
```

```{r political leaning and sexual orientation, fig.height=6, fig.width=7, echo = FALSE, include = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(political ,levels=c("Very liberal", "Somewhat liberal", "Moderate","Somewhat conservative", "Very conservative"))), fill = sexor))+
  geom_bar(position= "fill") +
  labs(title = "political leaning and sexual orientation", 
       x = "", y = "") +
  coord_flip() +
  theme_minimal()
```

```{r political leaning and fin aid, fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(political ,levels=c("Very liberal", "Somewhat liberal", "Moderate","Somewhat conservative", "Very conservative"))), fill = finaid))+
  geom_bar(position= "fill") +
  labs(title = "political leaning and financial aid status", 
       x = "", y = "") +
  coord_flip() +
  theme_minimal()
```

```{r pres vote and fin aid status, fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(president,levels=c("Howie Hawkins", "Jo Jorgenson", "Joe Biden","Donald Trump"))), fill = finaid))+
  geom_bar(position= "fill") +
  labs(title = "presidential vote and financial aid status", 
       x = "", y = "") +
  coord_flip() +
  theme_minimal()
```

```{r major and political leaning, fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = major, fill = (factor(political ,levels=c("Very liberal", "Somewhat liberal", "Moderate","Somewhat conservative", "Very conservative")))))+
  geom_bar(position= "fill") +
  labs(title = "intended major and political leaning", 
       x = "", y = "") +
  scale_fill_discrete(name = "political leaning") +
  coord_flip() +
  theme_minimal()
```

```{r}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(greek ,levels=c("Extremely interested", "Very interested", "Moderately interested", "Slightly interested", "Not interested at all"))), fill = (factor(political ,levels=c("Very liberal", "Somewhat liberal", "Moderate","Somewhat conservative", "Very conservative")))))+
  geom_bar(position= "fill") +
  labs(title = "interest in greek life & political leaning", 
       x = "", y = "") +
  scale_fill_discrete(name = "political leaning") +
  coord_flip() +
  theme_minimal()
```

```{r}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(slgs ,levels=c("Extremely interested", "Very interested", "Moderately interested", "Slightly interested", "Not interested at all"))), fill = (factor(political ,levels=c("Very liberal", "Somewhat liberal", "Moderate","Somewhat conservative", "Very conservative")))))+
  geom_bar(position= "fill") +
  labs(title = "interest in slgs & political leaning", 
       x = "", y = "") +
  scale_fill_discrete(name = "political leaning") +
  coord_flip() +
  theme_minimal()
```

```{r}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(greek ,levels=c("Extremely interested", "Very interested", "Moderately interested", "Slightly interested", "Not interested at all"))), fill = sexor))+
  geom_bar(position= "fill") +
  labs(title = "interest in greek life & sexual orientation", 
       x = "", y = "") +
  scale_fill_discrete(name = "political leaning") +
  coord_flip() +
  theme_minimal()
```

```{r}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = community, fill = (factor(political ,levels=c("Very liberal", "Somewhat liberal", "Moderate","Somewhat conservative", "Very conservative")))))+
  geom_bar(position= "fill") +
  labs(title = "community and political leaning", 
       x = "", y = "") +
  scale_fill_discrete(name = "political leaning") +
  coord_flip() +
  theme_minimal()
```

```{r}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = community, fill = (factor(president,levels=c("Howie Hawkins", "Jo Jorgenson", "Joe Biden","Donald Trump")))))+
  geom_bar(position= "fill") +
  labs(title = "community and political leaning", 
       x = "", y = "") +
  scale_fill_discrete(name = "political leaning") +
  coord_flip() +
  theme_minimal()
```

```{r}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(coviddeath,levels=c("Prefer not to say", "Yes", "No"))), fill = (factor(president,levels=c("Howie Hawkins", "Jo Jorgenson", "Joe Biden","Donald Trump")))))+
  geom_bar(position= "fill") +
  labs(title = "family/friend death from covid and presidential vote", 
       x = "", y = "") +
  scale_fill_discrete(name = "presidential vote") +
  coord_flip() +
  theme_minimal()
```

```{r legacy-and-income, fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = collegecoun, fill = (factor(income ,levels=c("Above $500,000","$250,000-$500,000", "$125,000-$250,000", "$80,000-$125,000","$40,000-$80,000", "Below $40,000")))))+
  geom_bar(position= "fill") +
  labs(title = "hired college counselor and income", 
       x = "", y = "") +
  scale_fill_discrete(name = "income level") +
  coord_flip() +
  theme_minimal()
```

```{r}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = college, fill = (factor(political, levels=c("Very liberal", "Somewhat liberal", "Moderate","Somewhat conservative", "Very conservative")))))+
  geom_bar(position= "fill") +
  labs(title = "community and political leaning", 
       x = "", y = "") +
  scale_fill_discrete(name = "political leaning") +
  coord_flip() +
  theme_minimal()
```

```{r fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(x = (factor(political, levels=c("Very liberal", "Somewhat liberal", "Moderate","Somewhat conservative", "Very conservative"))), fill = whyduke))+
  geom_bar(position= "fill") +
  labs(title = "x", 
       x = "", y = "") +
  coord_flip() +
  theme_minimal()
```

```{r fig.height=6, fig.width=7, echo = FALSE}
newfirst %>% 
  ggplot(newfirst, mapping = aes(fill = (factor(political ,levels=c("Very liberal", "Somewhat liberal", "Moderate","Somewhat conservative", "Very conservative"))), x = (factor(report, levels =c("Very likely", "Moderately likely", "Neither likely nor unlikely","Moderately unlikely", "Very unlikely")))))+
  geom_bar(position= "fill") +
  labs(title = "likelihood of reporting compact violations & political leaning", 
       x = "", y = "") +
  scale_fill_discrete(name = "political leaning") +
  coord_flip() +
  theme_minimal()
```